### ISSUE TITLE
Can you provide examples on how to use this library.

### ISSUE THREAD

**Issue by ghost** [richardschneider/net-ipfs-api#36]
I'm not advanced in C# and i'm seeing things I've never used before.

I'm trying to get a list of swarm peers.

**Comment by richardschneider** [comment]
> I'm not advanced in C# and i'm seeing things I've never used before

What are the things you never used before?

Have you read the [ISwarmApi](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.CoreApi.ISwarmApi.html) and [Peer](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.Peer.html) documentation?

**Comment by richardschneider** [comment]
An example
```csharp
var ipfs = new IpfsClient();
var peers = await ipfs.Swarm.PeersAsync();
foreach (var peer in peers)
{
  ...
}
```

**Comment by richardschneider** [comment]
@RyanJEC does the above answer your questions?
