### ISSUE TITLE
IPFS-Cluster AddDirectoryAsync

### ISSUE THREAD

**Issue by cmadh** [richardschneider/net-ipfs-api#39]
When adding a directory to an IPFS-Cluster, the DagNode is not added to the Peers. Only to the connected Api-Host. Endpoints of ipfs and ipfs-cluster differ. api/v0/add/ works on both, so each file is correctly added and pinned, the directory not. api/v0/object/put is not distributed by the ipfs-cluster.

**Comment by kthamm** [comment]
I'm running into the same issue. Adding a directory is working with `ipfs-cluster-ctl` and what I can tell from a tcpdump is that `ipfs-cluster-ctl add -r <dir>` performs a single request to `api/v0/add?recursive=true` but this api performs multiple adds and then a `api/v0/object/put`. I think this API should rather do it the same way as the official tools?

**Comment by richardschneider** [comment]
I've never encountered IPFS-Cluster before.  Can you point me to documentation?

How is a directory added to IPFS-Cluster?

**Comment by kthamm** [comment]
Documentation is on [cluster.ipfs.io](https://cluster.ipfs.io/documentation/). It is basically a service on top of ipfs with a http-proxy that catches requests documented [here](https://cluster.ipfs.io/developer/api/) and performs them for all nodes in the cluster. It aims to mimic responses to the ones by ipfs-http-api. So there _should_ be no difference in using them. However - as you can tell from the documentation - the endpoint `/object/put` is directly passed to the ipfs-api and not distributed by ipfs-cluster. Therefore the content is not available/added on all nodes. I tested the official [ipfs/js-ipfs-api](https://github.com/ipfs/js-ipfs-api) and it seems to upload directories by a single request to `/add?recursive=true`-endpoint and works fine with ipfs-cluster.

**Comment by cmadh** [comment]
seems like js-ipfs-api is doing a single Multipart-Post conatining all files, to api/v0/add?.
Docs here: https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filesadd 
and here: https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filesaddpullstream
Here is the multipart-wrapper: https://github.com/ipfs/js-ipfs-api/blob/master/src/utils/send-files-stream.js

**Comment by richardschneider** [comment]
@cmadh and @kthamm thanks for the information.

From my brief reading of `ipfs-cluster` it appears that it "emulates" the HTTP-API for a group of peers. 

I think it should support `api/v0/object/put` and also `api/v0/dag/put`.  Could you raise an issue there?

**Comment by richardschneider** [comment]
PS: `ipfs-cluster` should also support `api/v0/block/put`.
