### ISSUE TITLE
How to give support to ipfs.core for android 8.1 in xamarin forms...???

### ISSUE THREAD

**Issue by mosinms7711** [richardschneider/net-ipfs-api#44]
Hello...I am not unable to add IPFS.Core package in my android project...My Dependancy in .net Standard 2.0 and m targetting 8.1...Please help me out...

**Comment by richardschneider** [comment]
I have not tried Ipfs.Core with Xamarin.  Could you please give the errors?

Does Xamarin support .Net Standard 2? Have you read https://dzone.com/articles/xamarin-forms-and-net-standard-getting-started?

**Comment by richardschneider** [comment]
This may also help https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/net-standard

Also, are you trying to add ipfs.core of ipfs.api?  Please raise individual issues, my mind only has a few slots for issues.

If you have repo with the project, I'll fork it and try to get it to work.

**Comment by mosinms7711** [comment]
@richardschneider  Thanks for help.can you please tell me...How to wrap data in Merkle Dag with xamarin forms or c#.?I need to add content to ipfs network.Before that i want hash value for the content.Now i can get hash values of raw data but when we add content to ipfs it wrap the data with merkle dag then create hash value of the content before uploading to ipfs n/w.

**Comment by richardschneider** [comment]
The easy way is to simply call [FileSystem.AddFileAsync](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.CoreApi.IFileSystemApi.html#Ipfs_CoreApi_IFileSystemApi_AddFileAsync_System_String_Ipfs_CoreApi_AddFileOptions_System_Threading_CancellationToken_).  It returns a FileSystemNode which contains the `Id`.  The ID is a CID (Content ID) which in the normal case, v0, is the multihash.

```csharp
using Ipfs.Api;

var ipfs = new IpfsClient();
var path = "path-to-file";
var node = await ipfs.FileSystem.AddFileAsync(path);
var hash = (string)node.Id;
Console.WriteLine($"The hash is {hash}");
```

**Comment by mosinms7711** [comment]
@richardschneider  thank for help...for the jpeg image above code gives different hash value than IPFS add.Can you please help me with the same.?

**Comment by richardschneider** [comment]
Please show what `IPFS add `returns and what the above code prints.  Also please attach the image.

I did test this on my machine and it worked.

**Comment by richardschneider** [comment]
The new documentation on the [client](https://richardschneider.github.io/net-ipfs-api/articles/client.html) and the [file system](https://richardschneider.github.io/net-ipfs-api/articles/filesystem.html) may help.
