### ISSUE TITLE
proposed Module rename. -api => -http-client

### ISSUE THREAD

**Issue by daviddias** [richardschneider/net-ipfs-api#48]
Hi! We are considering renaming the IPFS Client libraries, please read more at https://github.com/ipfs/ipfs/issues/374 and comment if you are onboard.

**Comment by richardschneider** [comment]
Yes you have a very good idea here.  From the last reading it seems the consensus is `ipfs-http-client`.

Please inform me when everything is agreed upon.

**Comment by richardschneider** [comment]
> There are only two hard things in Computer Science: cache invalidation and **naming things**.

**Comment by daviddias** [comment]
@richardschneider we've reached a good enough quorum. Please rename to net-ipfs-http-client. Thank you for being onboard of this update :)

**Comment by richardschneider** [comment]
The following needs to done

- [x] update nuget with a note that this is now called `Ipfs.Http.Client`
- [x] change namespace to `Ipfs.Http`
- [x] change assembly to `Ipfs.Http.Client`
- [x] change Github repo to `net-ipfs-http-client`
- [x] release `Ipfs.Http.Client` to nuget
- [x] update hyper-links in other projects
- [ ] change the [server](https://github.com/richardschneider/net-ipfs-engine/tree/master/IpfsServer) to use `Ipfs.Http.Server`

**Comment by richardschneider** [comment]
Waiting for https://help.appveyor.com/discussions/problems/18344-renaming-github-repo to be resolved.
