### ISSUE TITLE
NuGet package dependencies 

### ISSUE THREAD

**Issue by gardient** [richardschneider/net-ipfs-api#5]
so brand new install from NuGet, gets dependencies automatically, and gives this.

```
Could not load file or assembly 'Ipfs.Core, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.
```

You either have to update the dependencies on the package or stop hard linking to a version (is that even possible?). Not sure how you do either of those never actually made a nuget package.

not a big problem, just annoying

**Comment by richardschneider** [comment]
Thanks, will fix and make a new release.

**Comment by gardient** [comment]
~~I'm sorry but you really need to get your dependencies straight.~~

I would really like it if you had the proper dependencies on your packages.

v0.6.0 of the nu-get package needs v0.6.1 of net-ipfs-core, otherwise it fails to load IMerkleNode from core

**Comment by richardschneider** [comment]
Sorry, fixed in [Ipfs.API v0,6,1](https://www.nuget.org/packages/Ipfs.Api/0.6.1)
