### ISSUE TITLE
AddFileAsync() not adding file to webui

### ISSUE THREAD

**Issue by sanjay-ipfs** [richardschneider/net-ipfs-api#54]
I'm using the AddFileAsync() function to add files to IPFS. But it is adding file to the local ipfs but not to webui (I guess not adding to MFS). I tried to view the the added file in http://127.0.0.1:5001/webui files list, but not added. Can you help me out in this...

**Comment by richardschneider** [comment]
You are correct, AddFileAsync() will add the block(s) to the local IPFS node.  The node then adds a `FindProvider` record to the DHT, which other nodes can then use to find the block.

Which daemon are you running go, js or cs?

**Comment by sanjay-ipfs** [comment]
I'm using the go daemon and cs-http-api

> You are correct, AddFileAsync() will add the block(s) to the local IPFS node. The node then adds a `FindProvider` record to the DHT, which other nodes can then use to find the block.

So, how can I add the files, so that I can view them in webui?

**Comment by richardschneider** [comment]
At the top of each page in WebUI, there is a `QmHash` box.  Enter the CID of your file and press `Explore`.
