### ISSUE TITLE
Managing files in local IPFS Node

### ISSUE THREAD

**Issue by shawnsblog** [richardschneider/net-ipfs-api#56]
Is there a way to determine which hashes belong to the local IPFS node entry point?

I was looking for a ListFilesAsync as part of a IFileSystem, that might return an array of filehashes, however wasn't able to. Thoughts?

**Comment by richardschneider** [comment]
You can use [IPinApi.ListAsync](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.CoreApi.IPinApi.html#Ipfs_CoreApi_IPinApi_ListAsync_System_Threading_CancellationToken_) to get all CIDs that have been locked on the local IPFS node.
