### ISSUE TITLE
ReadFileAsync() not return value when its using in Xamarin app.

### ISSUE THREAD

**Issue by intfloatbool** [richardschneider/net-ipfs-api#57]
![image](https://user-images.githubusercontent.com/40067295/62785114-99ea3780-bac8-11e9-87fe-d01e7079d6c5.png)

In the Standalone version it working great, but in running android Xamarin app its looks like infinity....

**Comment by richardschneider** [comment]
What do you mean by `Standalone version`?  

BTW Xamarin has never been supported.

**Comment by intfloatbool** [comment]
I meant just WPF ;-D Sorry for stupid issue-rerport, i didnt understand how IPFS works at all... Now problem is solved, but not Xamarin, becouse we need a run daemon before using IPFS, so i use java now (to access run ipfs daemon-task in adnroid)
