### ISSUE TITLE
Port library to .NET Core?

### ISSUE THREAD

**Issue by piravp** [richardschneider/net-ipfs-api#7]
Will this package be available for .NET Core in near future?

**Comment by richardschneider** [comment]
I haven't been playing with C# for some time.  Could you recommend article(s) that describe porting to .Net Core.

**Comment by piravp** [comment]
I had a look earlier and found this:
[http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/](http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/)

I ran your repo through [this](https://icanhasdot.net/) tool and it appears some of the dependencies aren't supported in .NET Core.

**Comment by piravp** [comment]
Do you know how to write this over to a .NET Standard Class Library? Then it could run on any .NET runtime (e.g. Xamarin for mobile development)?

**Comment by richardschneider** [comment]
Yes, .NET standard is the way to go.  But i must port [IPFS Core](https://github.com/richardschneider/net-ipfs-core). See issue https://github.com/richardschneider/net-ipfs-core/issues/26

**Comment by piravp** [comment]
Awesome, can't wait! 👍 
> All changes are in the netstandard branch.

Can't find any `netstandard ` branch, so I'm assuming it's coming in the near future? 

I'm working on a Xamarin project (that depends on IPFS) which is on hold awaiting these two libraries. Do you think you can give an estimate for how much time it will take for you to port those two libraries to .NET Standard? 

Really appreciate the work you're doing here!

**Comment by richardschneider** [comment]
Just pushed the branch for Ipfs.Core.  Some dependent libraries are not available for .Net Standard but they do work!  I'm expecting a week or so, need to get tooling (docomentation, coverage, CI, ...) working.

I assume you are running on Linux.  Would you mind creating a build script for Ipfs.Core?

Thanks for pushing me to support other platforms.

**Comment by piravp** [comment]
Sounds good.

No, I'm not running Linux, unfortunately.

**Comment by hitchhiker** [comment]
@richardschneider are you referring to a fully managed version of the IPFS project, one written in C# from scratch? or an api consumer for the existing Go project?

**Comment by richardschneider** [comment]
It's an API consumer.

**Comment by richardschneider** [comment]
@piravp I've published [Ipfs.Api 0.8](https://www.nuget.org/packages/Ipfs.Api) which supports .NET Standard 2.0 and .NET Framework 4.5.

Hopefully, its what you need.  Please inform me about it.

**Comment by piravp** [comment]
@richardschneider Thank you for the quick implementation. 

I'll have a look and let you know.

**Comment by piravp** [comment]
@richardschneider Is is possible to support a lower .NET Standard (1.6)? 
.NET Standard support table:
https://developer.xamarin.com/guides/cross-platform/application_fundamentals/net-standard/ 

.NET Standard 2.0 seems to only support Android 8.0 (which is not widely available)

**Comment by richardschneider** [comment]
I'm targeting .NET Standard 2.0 because it allows assemblies compiled to .NET Framework to still be used.  Base32, Base58Check and SHA3 are used by net-ipfs-core

**Comment by richardschneider** [comment]
@piravp I've published [Ipfs.Api 0.9](https://www.nuget.org/packages/Ipfs.Api) which adds support for .NET Standard 1.6.  Hope if helps.  Please give feedback.

**Comment by piravp** [comment]
I'm having problems installing Ipfs.Api because of SHA3 - I keep getting this error: 

>Could not install package 'SHA3 0.9.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	


Do you know which .NET framework/standard `SHA3 0.9.2` targets?

**Comment by richardschneider** [comment]
Can you show me your project? Is it open source.  If not could I see the .csproj?

**Comment by richardschneider** [comment]
From this [document](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) it appears that `monoadroid`  uses .NET Standard 1.4

**Comment by piravp** [comment]
So it appears Ipfs.Api 0.9.0 isn't going to work unless it's in .NET Standard 1.4?

**Comment by richardschneider** [comment]
I really don't know. I haven't worked with Mono (Xamarion).  I'll try to build to 1.4 and you can test.  Give me a few hours.

**Comment by richardschneider** [comment]
@piravp I've published [Ipfs.Api 0.9.1](https://www.nuget.org/packages/Ipfs.Api) which adds support for .NET Standard 1.4. 

Make sure you are using latest version of nuget: 

```
> nuget update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.3.0.
NuGet.exe is up to date.
```

Can I make a fork of your project, so I can test locally?

**Comment by piravp** [comment]
I have done all the testing in a separate project to not mess things up. 
So I have pushed the test project to GitHub: https://github.com/piravp/TestIpfsOnAndroid

I'm getting the same error as earlier (about SHA3) even with Ipfs.Api 0.9.1...

**Comment by richardschneider** [comment]
Porting to .NET core/standard is done.

I've opened a new issue #9 for Xamarian projects, which has a work around.
